# Generated by Django 4.2.5 on 2023-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scraping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="tag", name="quotes",),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="web_scraping.tag"),
        ),
    ]
