# Generated by Django 4.2.5 on 2023-09-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_scraping", "0003_author_remove_quote_author_quote_authors"),
    ]

    operations = [
        migrations.RemoveField(model_name="quote", name="authors",),
        migrations.AddField(
            model_name="quote",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_scraping.author",
            ),
        ),
    ]
